### ISSUE TITLE
fetch, analyze: optional dir flag

### ISSUE THREAD

**Issue by Deleplace** [eliben/so-tag-sentiment-analysis#5]
It would be nice to let the user omit the command-line flag "dir", with an implicit convention dir e.g. "./data". This seems reasonable enough to fit most common needs.

The convention has the advantage of omitting `-dir` in both fetch and analyze phases, while still referring to the same dir.

We still want fetch to create the folder, if not exist.

We still want analyze to fail, if the folder doesn't exist.

**Comment by Deleplace** [comment]
Some alternatives would automatically create temp dir in the OS temp folder. But I don't consider this would bring benefits. Just write the data close to the program!

**Comment by eliben** [comment]
Not sure about this one. You'll need to be careful where you run this code - `data` could be erased/overwritten otherwise (I assume this is relative to cwd). In practice having this flag passed in is not a big deal.

In general, being able to run with no flags and all defaults is a bit overrated IMHO. I almost never type the commands anew - 99% of invocations are [from history](https://eli.thegreenplace.net/2013/06/11/keeping-persistent-history-in-bash/) (with modifications).

**Comment by Deleplace** [comment]
Let's make `-dir` mandatory in analyze then
